### ISSUE TITLE
Support for vex-js v4

### ISSUE THREAD

**Issue by altschuler** [shlomiassaf/ngx-modialog#384]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Vex [v4](https://github.com/HubSpot/vex/releases/tag/v4.0.0) introduced a breaking change in the required DOM structure. The release notes include:

> The `.vex-overlay` element now sits next to the `.vex` element, instead of as a child.

**Comment by shlomiassaf** [comment]
Hi

Started working on it [see this branch](https://github.com/shlomiassaf/ngx-modialog/tree/feat(vex)/initial-support-for-v4)

The change in DOM structure requires a big change in the code and I'm not sure I can support vex backwards.

The branch 95% ready the only issue is with in-element support that seems to be a problem that will require a complete DOM structure change (within the library) in order to support that.

**Comment by altschuler** [comment]
Fantastic! I'm not sure what in-element support means?

**Comment by shlomiassaf** [comment]
In the demo app you can see that you can "contain" a modal within an element.

**Comment by shlomiassaf** [comment]
Have to say, looks like a substantial change, I'll have to see how time it will take.

PRs on that branch are welcome

**Comment by shlomiassaf** [comment]
Will publish version 4.0.0-beta.2 shortly.

Unfortunately **ngx-modialog** version 4+ supports Angular 5+ , angular 4 will not work.

This is due to breaking changes in angular 5

**Comment by altschuler** [comment]
Oh wow, that was fast! Thank you very, very much!

**Comment by shlomiassaf** [comment]
@altschuler FYI, version 3.0.3 (that works with angular 4) supports VEX 4 now

**Comment by altschuler** [comment]
Fantastic, just tried it out and it just works :tada:
