### ISSUE TITLE
Version 4.x.x of the library is not compatible with Angular 4

### ISSUE THREAD

**Issue by erzaehlsalex** [shlomiassaf/ngx-modialog#385]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

The library is no more compatible with Angular 4. I'm using Angular 4.x and I installed the version 4.0.0-beta.1 of the ngx-modialog library. Now the following stack trace appears when I'm trying to open a modal.

`ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.Injector.create is not a function at DOMOverlayRenderer.webpackJsonp../node_modules/ngx-modialog/bundle/ngx-modialog.es5.js.DOMOverlayRenderer.render`

The problem is that `Injector.create` was introduced in Angular 5 beta 3. So right now, it is not possible to use the library with an angular version below 5 beta 3. Is there a workaround that you could provide by any chance?

Thanks in advance

**Comment by shlomiassaf** [comment]
The problem with angular 5 is deprecating support for `ReflectiveInjector` which is a big thing since the library used `ReflectiveInjector` when creating dialogs.

Creating a deprecation path from 4 to 3 is time consuming so I couldn't support that.

There is a tag for version [3.0.2](https://github.com/shlomiassaf/ngx-modialog/tree/3.0.2), if you want to add some of the fixes created since then we can do that by creating a branch and PR's into it. I will publish the npm package for that...

**Comment by erzaehlsalex** [comment]
Great, can you please create a new branch for that? So I can fix #379 on this branch and commit it, so you can publish that on npm. This would be awesome!

**Comment by shlomiassaf** [comment]
https://github.com/shlomiassaf/ngx-modialog/tree/v3.0.2
