### ISSUE TITLE
Use inline templates

### ISSUE THREAD

**Issue by troyanskiy** [shlomiassaf/ngx-modialog#392]
You have closed my PR #368 
Seems you still have not inline templates
Check file ngx-modialog.webpack.umd.js L: 2935
![image](https://user-images.githubusercontent.com/1538862/29810857-c627cb98-8ca1-11e7-8635-5d5bdcc6807d.png)

**Comment by shlomiassaf** [comment]
@troyanskiy I really don't understand why you insist.

This is a plunker for ngx-modialog version 3.0.3 (after JUN 20): http://embed.plnkr.co/2ppVYl517GI1Byv8vVbG/

As you can see it is working fine (and it's using the UMD bundles)

The image you pasted here shows UMD bundle from the file `ngx-modialog.webpack.umd.js` which is is not the UMD bundle being used, the actual UMD used is `ngx-modialog.rollup.umd.js` and this is set in the `package.json` file.

The webpack UMD bundle is there due to old setup but it's incorrect has a wrong setup and along with not inlining resources it also bundles external packages such as `rxjs` (due to improper setup).

> Even with proper setup the rollup UMD is better in performance and size.

**Comment by shlomiassaf** [comment]
Please close this issue, everything is fine.

**Comment by troyanskiy** [comment]
@shlomiassaf You are right!
I was confused with that webpack and rollup umd's...
Using rollup everything is ok.

Thank you!
